version: '3'
services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kyouzai_development
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/kyo-zai
      - gem_data:/usr/local/bundle
    ports:
      - "3001:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    env_file:
      - .env

  front:
    build: ./front
    command: yarn start
    ports:
      - '3000:3000'
    volumes:
      - ./front:/kyo-zai
    depends_on:
      - api

volumes:
  mysql-data:
  gem_data:
    driver: local
